sudo: required
dist: trusty
services:
  - docker

before_install:
  - docker pull xyzsam/smaug

language: c
compiler:
  - gcc

script:
  - docker run --rm -v $PWD:/workspace/smaug:rw xyzsam/smaug /bin/bash -c "cd smaug && ./run_travis.sh"

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - samxi@seas.harvard.edu
